### ISSUE TITLE
SouceLink for SVN server

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/sourcelink#203] opened 2018-11-05 10:13 UTC
Hi,
Is it possible to provide source link from SVN server installed locally.

Thanks and regards
Venkatesh

**Comment by tmat** [comment] 2018-11-24 23:40
It should be possible to implement if anyone is interested in doing so.

**Comment by tmat** [comment] 2018-12-22 13:34
Duplicate of https://github.com/dotnet/sourcelink/issues/184

**Closed by tmat** 2018-12-22 13:34 UTC
Labels: duplicate, up-for-grabs

**Comment by WenningQiu** [comment] 2020-10-01 20:35
@VenkateshSrini We had the same issue, you might want to check out https://www.nuget.org/packages/SourceLink.VisualSVN/1.0.0
