### ISSUE TITLE
Building a .NET Core 3.1 project results in MSB4062

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/sourcelink#524] opened 2019-12-04 12:52 UTC
Hi,

After upgrading my solution to .NET Core 3.1, I've started to notice that my builds are failing due to sourcelink? Can anyone elaborate on what the issue is, and can I work around this in any way?

**Core.Serialization.csproj**
```
<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <OutputType>library</OutputType>
    <IsPackable>true</IsPackable>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>  

  <ItemGroup>  
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
    <PackageReference Include="protobuf-net" Version="2.4.0" />
    <PackageReference Include="Microsoft.SourceLink.Vsts.Git" Version="1.0.0-beta2-19367-01" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\core-pkg\src\Core\Core.csproj" />
  </ItemGroup>
</Project>
```

**Build output**
```
error MSB4062: The "Microsoft.Build.Tasks.Git.LocateRepository"
task could not be loaded from the assembly 
/root/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19367-01/build/../tools/netcoreapp2.0/Microsoft.Build.Tasks.Git.dll. 
Assembly with same name is already loaded Confirm that the 
<UsingTask> declaration is correct, that the assembly and all its dependencies are available,
and that the task contains a public class that implements Microsoft.Build.Framework.ITask
```

**Comment by WeihanLi** [comment] 2019-12-08 07:37
the same question met with version `1.0.0`

**Comment by stuart-blackler-cko** [comment] 2019-12-13 09:15
I've also found that this happens with `1.0.0-beta2-19554-01` also

**Comment by WeihanLi** [comment] 2019-12-13 09:27
the `1.0.0-beta2-19367-0` version worked for me, but above versions and `1.0.0` crashed, there's a sample project here <https://github.com/WeihanLi/AccessControlHelper/blob/dev/Directory.Build.props>

**Comment by tmat** [comment] 2019-12-21 00:36
@mmisztal1980 @WeihanLi Would you mind sharing a binary log (when using 1.0.0 Source Link version)? You can produce one by calling `dotnet build /bl`. The log includes details of your environment so you might not want to share it publicly. You can send it to tomat@microsoft.com.

**Comment by WeihanLi** [comment] 2019-12-23 02:05
Hi @tmat , sorry for my late reply, just tried but could not reproduce the exception with `1.0.0`, sorry for your time

**Comment by tillig** [comment] 2020-01-22 21:31
@tmat I just hit this with a solution that has all netcoreapp3.1 libraries and one netstandard2.0 library. They all reference Microsoft.SourceLink.AzureRepos.Git 1.0.0. I will send you a log shortly via email.

**Comment by tmat** [comment] 2020-01-23 02:13
It seems that the build process has multiple versions of Microsoft.Build.Tasks.Git.dll loaded for some reason (or rather it has one and is attempting to load another). I'm not sure why this would be a problem. @rainersigwald Shouldn't this problem have been fixed on .NET Core? 

As a workaround I'd try to 
1) update all projects to 1.0.0 version of Source Link
2) kill all `dotnet.exe` processes before the build

**Comment by tmat** [comment] 2020-01-23 02:15
Actually, it seems that one project loads 
`microsoft.build.tasks.git/1.0.0/build/../tools/netcoreapp2.0/Microsoft.Build.Tasks.Git.dll` successfully, but other projects in the solution do not. Very odd.

**Comment by rainersigwald** [comment] 2020-01-23 16:59
@tillig had you previously built a solution that used a different version of `Microsoft.Build.Tasks.Git`? This part

> Actually, it seems that one project loads
`microsoft.build.tasks.git/1.0.0/build/../tools/netcoreapp2.0/Microsoft.Build.Tasks.Git.dll` successfully, but other projects in the solution do not.

could be explained by MSBuild node reuse: newly-created nodes can load the 1.0.0 version fine; older ones had a different version loaded and failed.

Prior to .NET Core SDK 3.1.200 (not yet released), MSBuild could only load one version of an assembly in the lifetime of the process. By default, worker nodes live past the build invocation that created them. This is a bad combination! But should be fixed in the future by https://github.com/microsoft/msbuild/pull/4916.

**Comment by tmat** [comment] 2020-01-23 17:04
@rainersigwald That would explain. Thanks!

**Closed** 2021-01-21 12:37 UTC
Labels: external
