### ISSUE TITLE
'SourceRoot.SourceLinkUrl is empty' error running on Azure Pipelines (VSTS) agent configured with new URL

### ISSUE THREAD

**Issue by flcdrg** [dotnet/sourcelink#190] opened 2018-10-10 23:50 UTC
I have an Azure DevOps (aka VSTS) organisation that existed prior to the recent naming change.

I recently configured a new build agent following the instructions here https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=vsts#download-and-configure-the-agent - specifically I used the server url format https://dev.azure.com/{your-organization}

When trying to build our solution that references the Microsoft.SourceLink.Vsts.Git package, it failed with the following error:

`C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.sourcelink.common\1.0.0-beta-63127-02\build\Microsoft.SourceLink.Common.targets(40,5): error : SourceRoot.SourceLinkUrl is empty`

Cracking open the msbuild.binlog shows the following data for the Microsoft.SourceLink.Vsts.Git.GetSourceLinkUrl task:

```
Microsoft.SourceLink.Vsts.Git.GetSourceLinkUrl
    Assembly = C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\microsoft.sourcelink.vsts.git\1.0.0-beta-63127-02\build\..\tools\net461\Microsoft.SourceLink.Vsts.Git.dll
    Parameters
        RepositoryUrl = https://organisation.visualstudio.com/MyProject/_git/MyProject
        SourceRoot
            C:\agent\_work\2\s\
                            MappedPath=C:\agent\_work\2\s\
                            RepositoryUrl=https://dev.azure.com/organisation/MyProject/_git/MyProject
                            RevisionId=2a6a036a6ebef2a7966404a53ec02168a3859465
                            ScmRepositoryUrl=https://dev.azure.com/organisation/MyProject/_git/MyProject
                            SourceControl=git
        Hosts
            visualstudio.com
            vsts.me
        IsSingleProvider = True
    OutputProperties
        _SourceLinkUrlToUpdate = N/A
```

It struck me as suspicious that the RepositoryUrl parameters are different.

I ended up reinstalling the build agent and this time configured it with a server URL using the old format (https://organisation.visualstudio.com) and this error no longer happened.

That's probably not a long term solution given that the plan is to move everyone over to the new naming standard, so I think Microsoft.SourceLink.Vsts.Git might need to account for this 'mixed' mode of repository names.

**Comment by onovotny** [comment] 2018-10-13 18:47
I'm getting this as well and it's blocking things.

**Comment by onovotny** [comment] 2018-10-13 18:52
I believe the solution is to add

`<SourceLinkVstsGitHost Include="dev.azure.com" />` to here: https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.Vsts.Git/build/Microsoft.SourceLink.Vsts.Git.props#L7

In the interim, adding 
```xml
  <ItemGroup>
    <SourceLinkVstsGitHost Include="dev.azure.com" />
  </ItemGroup>
```
to the project file should work

**Comment by onovotny** [comment] 2018-10-13 18:57
Confirmed. I'll submit a PR later today.

**Comment by onovotny** [comment] 2018-10-17 12:58
@tmat any thoughts on getting the right tests in place for this?

**Comment by af4jm** [comment] 2018-10-17 17:02
I'm seeing the issue building locally both with and without the SourceLinkGitVstsHost item, and Azure builds succeeding both ways... additionally, I had to add the RepositoryUrl property (with the https URL) because my ssh URL was erroring (probably because it wasn't translating it based on my ssh config file, but SourceLink should have the https URL anyway)

**Comment by tmat** [comment] 2018-10-17 17:08
@onovotny It'd need to be an integration tests since it's validating msbuild content of an props file - 
a variation of 
https://github.com/dotnet/sourcelink/blob/master/src/SourceLink.Git.IntegrationTests/VstsTests.cs#L19.

The URLs used in the test would need to be slightly different: 'https://{host}/test/test-org/_git/test-repo' instead of `https://test.{host}/test-org/_git/test-repo'.

**Comment by tmat** [comment] 2018-10-17 17:10
@af4jm Can you run `msbuild MyProject.csproj /bl:log.binlog` and share the log?

**Comment by af4jm** [comment] 2018-10-17 17:18
log.binlog attached from the build of 1 project with no cross-project dependencies
[log.zip](https://github.com/dotnet/sourcelink/files/2488502/log.zip)

**Comment by tmat** [comment] 2019-07-01 22:19
https://github.com/dotnet/sourcelink/pull/316 adds `dev.azure.com` to well-known hosts.
However, that doesn't seem to the real problem for @af4jm's project. The well-known hosts are used when the repository uses multiple different Source Link packages (e.g. Vsts and GitHub) and Source Link needs to figure out which URLs belong to which host (consider e.g. repository in Azure DevOps that has submodules hosted on GitHub).

@af4jm's project uses SSH URL `ssh://af4jm/v3/...`. @af4jm any chance you use host mapping in `ssh_config`?

**Comment by af4jm** [comment] 2019-07-02 01:07
yep... and not sure if I can get around it, since I go in with 2 different identities...

```
Host af4jm
    HostName ssh.dev.azure.com
    User af4jm
Host MyEmployer
    HostName ssh.dev.azure.com
    User MyEmployer
    Identityfile ~/.ssh/work_rsa
Host *
    Identityfile ~/.ssh/id_rsa
```

**Comment by tmat** [comment] 2019-07-02 01:21
OK, then your case would be fixed by this: https://github.com/dotnet/sourcelink/issues/279

**Comment by tmat** [comment] 2019-11-04 01:32
Closing as duplicate of #279

**Closed by tmat** 2019-11-04 01:32 UTC
