### ISSUE TITLE
TFS authentication issues

### ISSUE THREAD

**Issue by dracan** [dotnet/sourcelink#207] opened 2018-12-05 18:04 UTC
We're trying to use SourceLink for TFS (on-premise using Git for source control). We're using `Microsoft.SourceLink.Tfs.Git` in one of our test private nuget packages, and this builds correctly adding the sourcelink info. However, when I try to use this test package in another application, then step into the code (ie. using sourcelink), it fails.

Running Fiddler (when I try to step into the library) to look at the http request that Visual Studio is making to TFS, it's failing with a 401 from TFS.

If I use FiddlerScript to modify the request (effectively man-in-the-middling the sourcelink request that Visual Studio is making), and I explicitly add an `Authorization` header, this then works perfectly.

The authorization header I'm adding looks like this: "Authorization: Bearer ******"

Where ***** is the base64 encoding of "domain\ad-username:personalaccesstoken".

This hack makes SourceLink work in TFS as expected. It _didn't_ work if I used my AD password instead of a personal access token.

If I copy the URL that is being used into Google Chrome (even a fresh incognito window), this shows the source code (so works as expected). Fiddler sees this as a 200 response. If I replay this request again in Fiddler, it fails again with a 401 (although the request is _identical_). Likewise, if I "copy as curl" that successful (200) request from Chrome devtools and run that CURL outside of the browser, this fails with 401.

So it appears that Chrome (and IE) does something extra not in the request to authenticate with TFS. My machine is on the domain - so it's probably related to that.

So I'm now stuck on how to get SourceLink working _without_ using FiddlerScript to inject the `Authorization` header with my username and a personal access token. The fact that there's a `Microsoft.SourceLink.Tfs.Git` nuget package suggest that it _should_ work fine. Any ideas?

**Comment by tmat** [comment] 2018-12-05 18:08
@chuckries

**Comment by dracan** [comment] 2018-12-05 19:49
@chuckries Thank you for the quick reply!

> For on premise TFS, you are not using a .visualstudio.com or code.azure.com URL, correct?

No, we're using an internal machine name.

> Do you have the Git Credential Manager fallback enabled

This isn't enabled. I did try briefly checking it, and it didn't work - but I'll try again when I'm back in the office tomorrow - perhaps GCM just wasn't set up correctly.

> or your connection is not HTTPS, then it will not work.

It is HTTPS, but it's a self-signed certificate. My dev machine is a fairly recent Windows re-install, and I can't remember whether I re-added the self-signed cert to the trusted certificate store since the reinstall. I'm not on the machine now, so can't check. I'll check this tomorrow. Don't know if this would make a difference or not.

> If your TFS server does not accept Basic Auth

Do you mean basic auth in IIS?

Thanks again for your help,
Dan

**Comment by chuckries** [comment] 2018-12-05 20:24
> Do you mean basic auth in IIS?
I'm not actually sure how to answer this. If we can acquire credentials from GCM, we will send them as an HTTP Basic Authentication token in the request: https://en.wikipedia.org/wiki/Basic_access_authentication. I know that the acceptance of this type of auth is configurable by source services. I am not sure how on prem TFS is configured, so you'll just have to try it and see. Whoever manages your TFS  deployment may know more.

I am also fairly certain you'll need to add your self signed cert to the trusted certificate store.

**Comment by dracan** [comment] 2018-12-06 11:37
Looks like I had already added the self-signed cert to the trusted store.

Turning on GCM fallback didn't work, and I got the following error ...

![image](https://user-images.githubusercontent.com/567988/49581857-36ad7180-f94b-11e8-9be9-679528f8c723.png)

Using Git from the command line works as expected.

Looks like I'm experiencing similar issues as described in #176

**Comment by chuckries** [comment] 2018-12-06 18:03
@dracan I have some ideas on how to fix this issue, but they are not fully production ready yet. Would you be interested in trying out a private fix?

**Comment by dracan** [comment] 2018-12-06 20:12
@chuckries Yes, definitely. I'm not in the office now until Monday, but happy to try something out on Monday.

**Comment by chuckries** [comment] 2018-12-12 18:33
@dracan can you email me directly at chuckr@microsoft.com to continue this discussion?

**Comment by gvdm90** [comment] 2018-12-18 13:08
I also have this problem and need a way to let sourcelink work with on-prem TFS with authentication

**Comment by dracan** [comment] 2018-12-18 19:53
@zplan @gvdm90 - @chuckries has sent me a test DLL to trial a fix. I'm hoping to give this a go tomorrow, so will post whether it works or not on here too.

**Comment by tmat** [comment] 2018-12-25 10:01
Marking "external" as this is an issue with VS debugger auth, not Source Link package itself.

**Comment by jeroenlandheer** [comment] 2018-12-27 09:36
I'm guessing this is actually the same issue as with #176

**Comment by gvdm90** [comment] 2019-01-09 21:47
...and after translating the URL to HTTPS, wouldn't it have this same issue?

Il giorno mer 9 gen 2019, 22:38 Tomáš Matoušek <notifications@github.com>
ha scritto:

**Comment by jeroenlandheer** [comment] 2019-01-10 06:00
@gvdm90 yes it would, you're absolutely right. 

I should have been a bit more specific, "Visual Studio doesn't support SSH urls _for sourcelink requests_." ... hmm, do I smell a feature request? 🤔

**Comment by chuckries** [comment] 2019-01-10 08:00
The issue is that (as far as my current knowledge goes) there is no way to request a single file at a specific commit from a remote repository over the git+ssh protocol. git+ssh and ssh key authentication works well for cloning repos, but it does not work for accessing source at the granularity that Source Link does.

**Comment by gvdm90** [comment] 2019-01-30 09:19
Are there any updates on this issue?

**Comment by jeroenlandheer** [comment] 2019-01-30 12:49
@chuckries That's a good point. [I saw on SO a post about this](https://stackoverflow.com/questions/1125476/retrieve-a-single-file-from-a-repository), using `git archive`, that would be something like `git archive --remote=ssh://host/pathto/repo.git <commit> <filename.ext>`.

**Comment by sunahe** [comment] 2019-03-15 08:58
@chuckries Can we receive a confirmation from Visual Studio team that they will deliver a fix at all?

**Comment by chuckries** [comment] 2019-03-21 23:37
Sorry for the slow responses everybody, I have been very busy with other work. I am currently working on Source Link Auth, and we will ship improvements in the first update to VS 2019 (dev 16.1). I will update this thread when those preview become available. 

The new work will support Source Link for Windows Authentication scenarios (as opposed to just Basic Auth through GCM). The primary motivation for this is for those using on premises TFS servers that use Windows Authentication. This may light other auth scenarios, such as GitHub Enterprise or on prem GitLab instances that use LDAP authentication mechanisms (I cannot guarantee this as I do not know exactly how these services work with these auth providers, and I cannot set up the infrastructure to test).

I hope the community will try out this preview and continue to provide feedback.

**Comment by nuzolx** [comment] 2019-04-19 11:24
@chuckries It's avaible in Visual Studio 2019 version 16.1 Preview 1?

**Comment by chuckries** [comment] 2019-04-19 17:39
@nuzolx I was on vacation for a few weeks and the work I did for this was delayed until 16.1 Preview 2. I apologize for the miscommunication. I will update this issue once Preview 2 is available.

**Comment by olivierhelin** [comment] 2019-04-25 12:04
@chuckries thanks a lot! That's work with 16.1.0 Preview 2.0 :)

**Comment by nuzolx** [comment] 2019-04-25 13:02
> @chuckries thanks a lot! That's work with 16.1.0 Preview 2.0 :)

Same. Thanks @chuckries!

**Comment by chuckries** [comment] 2019-04-25 16:52
16.1 Preview 2 is out now at https://visualstudio.microsoft.com/vs/preview/.

**Comment by chuckries** [comment] 2019-04-25 16:52
@olivierhelin @nuzolx just to confirm, you are seeing authentication against on prem TFS work with 16.1 preview 2?

**Comment by chuckries** [comment] 2019-04-25 16:57
Closing this issue as it should be fixed with the latest preview. Please file new issues for other auth related problems.

**Closed by chuckries** 2019-04-25 16:57 UTC
Labels: external

**Comment by dp7g09** [comment] 2019-05-23 16:50
@chuckries Seeing the exact same issue (as described by @dracan ) and works if I use fiddler the way it has been suggested. I am using Visual Studio 2019 Version 16.1.0 with Azure DevOps Server (on-prem).

Shall we re-open this issue?

**Comment by chuckries** [comment] 2019-05-23 17:59
@dp7g09 can you give more details about your scenario? You can reply to me at directly at chuckr@microsoft.com if you don't want to answer these publicly.
1. What is the actual source control you are using? git? TFS?
2. What is the format you are using for your Source Link URL's? Are you using the Microsoft.SourceLink.Tfs.Git nuget pacakge? Do you have the latest version?
3. In VS, when you try to step in, do you see the 'No Source Page' that says Source Link Authentication fails? Are you able to click the link on that page that says try again with authentication? What happens then?

**Comment by dracan** [comment] 2019-05-23 18:44
@chuckries Just to add to @dp7g09's comment. He and I actually work at the same place, and he was testing with the exact same test nuget package (and TFS environment) that I tested with. This worked for me when I tried your custom Visual Studio DLL that you emailed to me, but doesn't seem to be working in the latest version of VS2019 (16.1.0).

**Comment by dp7g09** [comment] 2019-05-23 19:50
@chuckries A User Error (apologies)! Your point number 3, I had missed that it does ask for credentials there. It works now. Thanks for your prompt response.

I have provided a bit more details, in case it is easier to establish that this case works now. Thanks.
Thanks to @dracan too.

> @dp7g09 can you give more details about your scenario? You can reply to me at directly at [chuckr@microsoft.com](mailto:chuckr@microsoft.com) if you don't want to answer these publicly.
> 
> 1. What is the actual source control you are using? git? TFS?

Git

> 2. What is the format you are using for your Source Link URL's? Are you using the Microsoft.SourceLink.Tfs.Git nuget pacakge? Do you have the latest version?

```
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.Tfs.Git" Version="1.0.0-beta2-18618-05">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```


> 3. In VS, when you try to step in, do you see the 'No Source Page' that says Source Link Authentication fails? Are you able to click the link on that page that says try again with authentication? What happens then?

This is what I had missed! It works now. Clicking on the link, opens up a credentials prompt, where when I used my Azure DevOps Server credentials, SourceLink manages to get the specific source code to folder
`%localappdata%\SourceServer\<unique folder name>`
